<?php
/***************************************************************************  
 *                               extension.inc
 *                            -------------------                         
 *   begin                : Saturday, Feb 13, 2001 
 *   copyright            : (C) 2001 The phpBB Group        
 *   email                : support@phpbb.com                           
 *                                                          
 *   $Id: extension.inc,v 1.1 2005/06/19 04:59:48 bitweaver Exp $
 *                                                            
 * 
 ***************************************************************************/ 

if ( !defined('IN_PHPBB') )
{
	die("Hacking attempt");
}

//
// Change this if your extension is not .php!
//
$phpEx = "php";

$starttime = 0;

?>